# Required properties template, the file follows YAML syntax.
squirls:
  # Path to `data-directory` with Squirls databases & genome FASTA file.
  # If the directory has the following structure:
  # path/to/a_folder:
  #  |- 1902_hg19:
  #  |   |- 1902_hg19.assembly_report.txt
  #  |   |- 1902_hg19.fa
  #  |   |- 1902_hg19.fa.dict
  #  |   |- 1902_hg19.fa.fai
  #  |   |- 1902_hg19.phylop.bw
  #  |   \- 1902_hg19_splicing.mv.db
  #  \- 1902_hg38:
  #      |- 1902_hg38.fa
  #      ...
  #
  # then set `data-directory: path/to/a_folder`
  data-directory:
  # Genome assembly - choose from {hg19, hg38}
  genome-assembly:
  # Exomiser-like data version (1902 in examples above)
  data-version:


  #classifier:
  #  Which classifier to use
  #  version: v0.4.6
  #  Variant with longer REF allele will not be evaluated
  #  max-variant-length: 100
  #annotator:
  # Which splicing annotator to use
  #  version: agez

